name: Scheduled Empty Commit

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  empty_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create empty commit
        uses: peter-evans/create-commit@v4
        with:
          commit-message: "chore: scheduled empty commit [skip ci]"
          allow-empty: true
